### ISSUE TITLE
Change default values for message queue

### ISSUE THREAD

**Issue by DanielJean007** [osvenskan/posix_ipc#21]
Hi there. Thanks for the amazing lib.

Could you, please, provide some guidance as to how I can change the default values for the message queue?

I have used the command: sudo sysctl fs.mqueue for each file in /proc/sys/fs/mqueue/
My actual system reads: 
fs.mqueue.msg_default = 360
fs.mqueue.msg_max = 500
fs.mqueue.msgsize_default = 921646
fs.mqueue.msgsize_max = 1382500
fs.mqueue.queues_max = 25

At first, when I tried to create a new message queue posix_ipc wouldn't show these values. It kept on showing the previous default values.
Reading through the code I saw that you run the prober.py once at installation time. So I understood that I needed to reinstall posix_ipc.
When I did that posix_ipc read the new values, but when I try to create the message queue it shows this error:

Exception has occurred: OSError
This process already has the maximum number of files open

Is there anything else I need to do?
Thanks in advance.

**Comment by osvenskan** [comment]
@DanielJean007 What operating system are you on?

**Comment by DanielJean007** [comment]
Sorry, shoulda said before.

Here's my system (uname -a

`Linux PED-4243 5.0.0-29-generic #31~18.04.1-Ubuntu SMP Thu Sep 12 18:29:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by osvenskan** [comment]
@DanielJean007 So you get `OSError` when creating the queue?

I'd need to see  a full code sample to have a better idea of what's going on, but here's what I can tell you from what I know now.

The `posix_ipc` module is just a thin layer around a bunch of OS calls, so if you're getting "This process already has the maximum number of files open", it's Linux telling you that. `posix_ipc` is just passing along the message.

As you astutely observed, `prober.py` reads values from `/proc/sys/fs/mqueue` to establish `posix_ipc.QUEUE_MESSAGES_MAX_DEFAULT` and `posix_ipc.QUEUE_MESSAGE_SIZE_MAX_DEFAULT`. `prober.py` runs **when `posix_ipc` is compiled** (not installed). Once `posix_ipc` is compiled, those values can't change. If you're using the pre-compiled package provided by Ubuntu, then `prober.py` got its values from the machine where `posix_ipc` was built, not from your laptop. 

Those values are the default values passed for `max_messages` and `max_message_size` when you create a queue. Since you can override those default values when you create a queue, the values that `prober.py` discovers don't really matter except for convenience. 

Does that make sense?

**Comment by DanielJean007** [comment]
It does.
But still the problem that I can't create anything more than the system's default of msg_default=10 and msgsize_default=4k bytes (approximately).

Have you tried to set a message queue greater than those values in a Linux System like Ubuntu 18.04?

Thanks.

**Comment by osvenskan** [comment]
@DanielJean007 

I booted up my Ubuntu 16 VM (the closest thing I have to 18) and tried out a few scenarios. In that VM, `fs.mqueue.msg_max` was set to 10. When I tried to create a queue with more messages than that, I got `ValueError: Invalid parameter(s)` ---
```
>>> import posix_ipc
>>> mq = posix_ipc.MessageQueue(None, posix_ipc.O_CREX, max_messages=25)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid parameter(s)
>>> mq = posix_ipc.MessageQueue(None, posix_ipc.O_CREX, max_messages=8)
>>> 
```

I altered sudo `msg_max` to 50: `sysctl -w fs.mqueue.msg_max=50`. Then I opened a new Python session and I was able to create a queue with 25 and 51 messages. A queue with 51 messages failed with `Invalid parameter` again ---
```
>>> import posix_ipc
>>> mq = posix_ipc.MessageQueue(None, posix_ipc.O_CREX, max_messages=25)
>>> mq = posix_ipc.MessageQueue(None, posix_ipc.O_CREX, max_messages=50)
>>> mq = posix_ipc.MessageQueue(None, posix_ipc.O_CREX, max_messages=51)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid parameter(s)
```

So at least on my Ubuntu 16 VM, changes to `msg_max` affect what `posix_ipc` can do from Python. I suspect if changed other values like `msgsize_max` I would see the same behavior.

One thing that I notice is that you report that you're getting "This process already has the maximum number of files open". It looks suspicious to me that I'm getting `ValueError: Invalid parameter(s)` when I try to exceed the values set from `sysctl` and you're getting a different error message. I'm not so convinced that the problem you're seeing is due to an interaction with `sysctl` values. 

I'd be curious what you see if you reboot and then try the simple scenario I outlined above.

**Comment by osvenskan** [comment]
@DanielJean007 Unless you have an update on this, I'm going to close this ticket.

**Comment by psavery** [comment]
I ran into this same issue and did a little research.

It looks like there is a resource limit for message queues imposed on the user. See `RLIMIT_MSGQUEUE` [here](https://man7.org/linux/man-pages/man2/getrlimit.2.html).

There is also some math in that description that shows how the number of bytes is calculated. With the defaults in Ubuntu (`RLIMIT_MSGQUEUE` == 819200 bytes, `msg_default` == 10, and `msgsize_default` == 8192), this roughly leads to 10 message queues allowed at a time. If you try to open one more (via a command such as `posix_ipc.MessageQueue(None, posix_ipc.O_CREX)`), you get the `OSError: This process already has the maximum number of files open`.

@osvenskan, the `ValueError: Invalid parameter(s)` you were encountering happens if you try to set `max_messages` to be greater than `msg_max` in `/proc/sys/fs/mqueue/`, which you cannot do without root privileges.

Unfortunately, you can't increase `RLIMIT_MSGQUEUE` without root privileges either, and I am working on some systems without root privileges. But if you need more message queues, one thing you can do is to decrease `max_messages` (defaults to `/proc/sys/fs/mqueue/msg_default`) or `max_message_size` (defaults to `/proc/sys/fs/mqueue/msgsize_default`) when you instantiate the queues. If, for instance, you decrease the `max_messages` to 1 for each of your queues, that allows you to create nearly 100 message queues before you start encountering the `OSError`.

This limitation is unfortunate, but I don't think there is much we can do about it other than decreasing the amount of bytes each queue takes when we make them.

**Comment by osvenskan** [comment]
Thanks @psavery for sharing that research.
