### ISSUE TITLE
Problem of messageQueue on macos

### ISSUE THREAD

**Issue by p4sh4bsc** [osvenskan/posix_ipc#49]
Hello, I would like to know why I don't have a messageQueue on macos. However, if I use this library on Ubuntu, then messageQueue can be used. Is this a problem on my side or it just the lib doesn't support messageQueue on macOS? I have already tried all possible solutions and searched for information of this problem in many sources, but I did not find the answer. I hope that you will give me an answer to my question, thanks!
<img width="600" alt="Снимок экрана 2023-07-14 в 02 35 47" src="https://github.com/osvenskan/posix_ipc/assets/120973158/1b872fa6-1e18-42a4-8fdb-4d2ee9c5c6f8">
<img width="600" alt="Снимок экрана 2023-07-14 в 02 36 26" src="https://github.com/osvenskan/posix_ipc/assets/120973158/49198262-19c0-46fe-b145-866a5a2d040e">

**Comment by osvenskan** [comment]
Привіт! You are correct, message queues are not supported on Mac because Apple has chosen not to implement POSIX message queues on Mac OS. This library is just a Python wrapper around operating system features, so if the operating system doesn't support it, this library can't support it either. 

This behavior is documented here: https://github.com/osvenskan/posix_ipc/blob/develop/USAGE.md#platform-notes

**Comment by p4sh4bsc** [comment]
ok, thanks for the reply
